### ISSUE TITLE
ETA for Typesetting

### ISSUE THREAD

**Issue by Darkneon** [MyScript/MyScriptJS#1]
I'm interested in this feature, is there a planned release date for it? Is there anything that can be done to help with this feature?

**Comment by rookoolcedric** [comment]
Hi Robert, 
we are happy to have you dig into our lib.

We are currently working on the typesetting feature but it is quiet early to elaborate on it for now.

Please, stay tuned we will keep you posted. 
Cédric

**Comment by padewitte** [comment]
The 4.0.0 version is bringing the `convert()` function that brings typesetting to MyScriptJS. Please give a try we will be glad to ear your feedback.
