### ISSUE TITLE
Issue writing on iPad and Chrome Device Emulator

### ISSUE THREAD

**Issue by dylanjmcdonald** [MyScript/MyScriptJS#10]
MyScriptJS Version: v4.0.0

I'm running into an issue on my iPad and the chrome device emulator where when I start to write something the pointer shoots to the upper left hand portion of the screen and ends the writing abruptly. The writing area works fine outside of the device emulator using a mouse.

[Screenshot](https://i.imgur.com/39jqfXW.png)

**Comment by RomainCscn** [comment]
This seems to be a pointer events issue. Did you include pepjs ? 
`<script src="https://code.jquery.com/pep/0.4.3/pep.js"></script>`

It's required for browsers and platforms that don't support pointer events.

**Comment by GiYung** [comment]
You need 'touch-action' attribute.

For example
`div touch-action="none">
    <nav>
        <button class="action-button" id="clear" disabled></button>
        <button class="action-button" id="undo" disabled></button>
        <button class="action-button" id="redo" disabled></button>
        <div class="spacer"></div>
        <button class="action-label-button" id="convert" disabled>Convert</button>
    </nav>
    <div id="editor"></div>
</div>
`

**Comment by dylanjmcdonald** [comment]
> This seems to be a pointer events issue. Did you include pepjs ?

pep.js is included.

> You need 'touch-action' attribute.

That did the trick. Thank you!
