### ISSUE TITLE
Offline version

### ISSUE THREAD

**Issue by mrandrey** [MyScript/MyScriptJS#11]
Is there an offline version that can be integrated into an app that could still work when the connection is offline?

**Comment by mathieuruellan** [comment]
Recognition is done on remote servers. If you have to develop an application working without being connected, you should consider native API (Android, IOS, Windows). 
https://developer.myscript.com/docs/interactive-ink/1.1/overview/about/

**Comment by mrandrey** [comment]
That's great, thanks. Can the native API for Android be used on a webview canvas?

**Comment by mathieuruellan** [comment]
We never experiment with hybrid applications. At least, it could be possible to create a binding with a Cordova/Phonegap plugin. We never tried, so i don't know if it's a dead end.

**Comment by mrandrey** [comment]
Sounds good. I'm not using Cordova/Phonegap, but I can experiment with using Android's JavaScript Interface. I'll dig around your API documentation.

On your requirements it says "Android SDK API 26 and higher (even if the libraries runs with Android SDK API 21 and higher)". I'm working on an Android 6.0 Implementation (API 23). Will it work as long as it's 21+ or is it only for 26+?

**Comment by thomaspenin** [comment]
The example code has `targetSdkVersion = 26` as we try to follow [Google's recommendation](https://developer.android.com/training/basics/supporting-devices/platforms.html) to always target the latest SDK. In the doc, the requirements to run the "Get Started" ask for SDK 26 for things to work out-of-the-box. In your case, if you set `targetSdkVersion = 23`, it should work without any problem.

**Comment by mrandrey** [comment]
Great, thanks.
