### ISSUE TITLE
Cordova plugins for ATK

### ISSUE THREAD

**Issue by bguiz** [MyScript/MyScriptJS#2]
[iOS & Android ATKs](https://dev.myscript.com/documentation/#ATK) are available.

Would like to know if Cordova plugins that wrap around these are in the works, or if 3rd parties should create & maintain these?

**Comment by padewitte** [comment]
We do not have any plan currently to add a cordova plugin to our product and we do not know any 3rd parties supporting it. If you want to quickly prototype handwriting recogntion in html page have a look to our webcomponents https://github.com/MyScript/myscript-text-web or https://github.com/MyScript/myscript-math-web .

**Comment by bguiz** [comment]
So I have started making my own cordova plugin.

I'm starting off with the single line text widget, and following the
instructions here:
http://doc.myscript.com/MyScriptATK/Android/sltw/index.html

```
Libraries

The following SDK libraries are required and need to be added:

libMyScript2D.so
libMyScriptEngine.so
libMyScriptText.so
```

Where can I find these *.so files? They don't appear to be within the ATK
files I have downloaded.
I there a separate download somewhere, and if so where can I find it?

So far what I have gathered is that:

1. sign up for a myscript ATK account & log into it
1. download "certificate"
1. download ATK binaries
1. replace files in ATK binaries with the downloaded certificate files
1. download SDK binaries from ???
1. create a project that includes both the ATK binaries and the SDK binaries

Have I missed out on any thing so far?


W: http://bguiz.com

On 27 November 2015 at 17:17, DEWITTE Pierre-Alban <notifications@github.com

**Comment by bguiz** [comment]
I found this page which promises an SDK, but I can't get just yet because I
have to send a request etc:
https://dev.myscript.com/pricing/sdk/

Is there a way for me to get the SDK in the same way I get an ATK?

W: http://bguiz.com

**Comment by bguiz** [comment]
This is where I am at with the plugin at the moment:
https://github.com/bguiz/myscript-cordova-plugin/blob/feature/init/package.json

The next step would be to create a `plugin.xml` file,
and for this I would need to know which `*.jar` files to include,
what the main class name for each of them is (maybe),
what folder they should be copied to.
I'll also need to add the `*.so` files from the SDK.

W: http://bguiz.com

**Comment by jwelmac** [comment]
Hey @bguiz!
Did you ever make any progress with the Cordova plugin?

**Comment by bguiz** [comment]
@jwelmac Nah, I wasn't able to get sufficient support from myscript devs regarding this, so I shelved development. I'm no longer using myscript as well, so it's unlikely I'll pick it up again.

**Comment by padewitte** [comment]
Wrapping our native lib in cordova component is not a trivial job. Currently we are not focusing our effort at MyScript on it.
I am closing this issue as it is not related to MyScriptJS
For any ATK question you can use our forum https://dev.myscript.com/forums/forum/atk/
