### ISSUE TITLE
Where can i get test key?

### ISSUE THREAD

**Issue by hanchao** [MyScript/MyScriptJS#4]

**Comment by Zetruenando** [comment]
Hi,
All you need to do is sign up for a free trial of MyyScript CDK on the developer portal: dev.myscript.com
Regards,
Zetruenando

**Comment by hanchao** [comment]
Thanks. I find it. It block in china.

**Comment by Zetruenando** [comment]
What is blocked? The web site, the registration process, the CDK activation, other? Assuming you can register, I recommend you use the forum on dev.myscript.com to best have your questions answered.

**Comment by hanchao** [comment]
CDK. https://www.google-analytics.com/analytics.js can not load
