### ISSUE TITLE
Docs are broken

### ISSUE THREAD

**Issue by aknoerig** [MyScript/MyScriptJS#6]
When opening `docs/index.html` in the browser, I'm just getting a directory listing. Also, `docs/api/index.html` is at least partly broken, since all the dynamic stuff isn't loading. And then there is the `docs/components` folder, which is basically just a copy of the bower_components.

Not sure if some setup steps are required? I did a `bower install`, a `npm install`, and a `gulp`, to no avail.

**Comment by F2X** [comment]
> docs/api/index.html is at least partly broken

This documentation is obsolete, you can find some documentation [here](http://doc.myscript.com/MyScriptCloud/3.0.0/myscript-web.html) and demonstrations [here](http://webdemo.myscript.com/).

> When opening docs/index.html in the browser, I'm just getting a directory listing

There is a dynamic redirection from `docs/index.html` to `docs/components/myscript/demo/index.html`, so if you want to run the sample, you can run `npm install && bower install && gulp serve` or directly going to `docs/components/myscript/demo/index.html`.

If you need more documentation for text recognition, you can get it from https://github.com/MyScript/myscript-text-web.
