### ISSUE TITLE
Provide more demos/examples

### ISSUE THREAD

**Issue by aknoerig** [MyScript/MyScriptJS#7]
The current demo is very reduced and doesn't show how to easily customize MyScriptJS further. For example, how do you switch the input mode to superimposed, how do you influence the rendering style, etc.

It seems the code shown in the demo video at https://dev.myscript.com/simplify-and-accelerate-hwr-web-projects-with-myscriptjs/ is much more configurable, but I cannot find the code anywhere.

**Comment by F2X** [comment]
We choose to push the use of the [text](https://github.com/MyScript/myscript-text-web) and [math](https://github.com/MyScript/myscript-math-web) web components for now.

If you want an example of superimposed configuration, using myscript-text-web, you can find one here: http://webdemo.myscript.com/views/contacts.html.
And our [webdemos](http://webdemo.myscript.com/) are based on webcomponents, so you can look at their source code for more implementation examples.

**Comment by aknoerig** [comment]
Thanks, I understand your focus is on the webcomponent solution now. 
Please make sure that your documentation clearly reflects this, though. ;)  At the moment, the situation around MyScriptJS is very confusing, with multiple documentation places, each with different versions and slightly different functionalities.

I'm looking for more of a barebones version because I assume it allows for deeper customization. In my case, for instance, I would like to replace the default touch input with a ws stream coming from an external input device.

**Comment by F2X** [comment]
Thanks for your feedback about the doc, we will improve it ;-)
The aim of the web components is to ease ink capture and rendering from a web page.
If you are just interested by the recognition part, without rendering, you will be probably more interested  by the cloud API. 
It will allow you to send your input stream directly to the web service and retrieve the raw result: http://doc.myscript.com/MyScriptCloud/3.1.0/myscript-cloud/protocols.html. 
Let me now if you need more help on this part.

**Comment by aknoerig** [comment]
Thanks, that's indeed also an option. But since MyScriptJS is basically the library for this API – and really well written ;) – I want to make use of that instead of reinventing the wheel.

I got it to work now by directly accessing the private _up/_down/_move functions. Not clean, but working fine.

**Comment by padewitte** [comment]
With the 4.0.0 version a significant list of examples have been add to the project. You can browse them [online](https://myscript.github.io/MyScriptJS/examples/)  or in the [project](https://github.com/MyScript/MyScriptJS/tree/master/examples)

Regarding the need of grabbing event externaly and the use the lib, `pointerDown(...)`,  `pointerMove(...)` and `pointerUp(...)` are now public and may ease the integration like yours. The coumentation is [online](https://myscript.github.io/MyScriptJS/docs/class/src/Editor.js~Editor.html#instance-method-pointerDown)
