### ISSUE TITLE
MyScript is undefined

### ISSUE THREAD

**Issue by EvertVerboven** [MyScript/MyScriptJS#9]
I get a undefinded error on line 58 of myscript.js, when requiring it in a javascript file

**Comment by padewitte** [comment]
Hi currently the lib is not ment to be used with require (this will come soon,  as you may notice in 2.0.0-alpha1 branch) . Can you import it with a script tag and then us it ?

**Comment by padewitte** [comment]
The problem is solved since [4.1.3 release](https://github.com/MyScript/MyScriptJS/releases/tag/v4.1.3).
See this working [example](https://github.com/MyScript/web-integration-samples)
